plugins {
    id 'java'
}

group = 'by.meshicage'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    set('lombok', '1.18.34')
    set('mockito', '5.5.0')
    set('junit', '5.10.0')
}

dependencies {
    compileOnly "org.projectlombok:lombok:${lombok}"
    annotationProcessor "org.projectlombok:lombok:${lombok}"

    testImplementation "org.junit.jupiter:junit-jupiter-api:${junit}"
    testImplementation "org.junit.jupiter:junit-jupiter-params:${junit}"
    testImplementation "org.mockito:mockito-core:${mockito}"
    testImplementation "org.mockito:mockito-junit-jupiter:${mockito}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junit}"
}

test {
    useJUnitPlatform()
}